[package]
name = "futures-concurrency"
version = "6.0.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/futures-concurrency"
documentation = "https://docs.rs/futures-concurrency"
description = "Concurrency extensions for Future"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>"
]

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
futures-core = "0.3"
pin-project = "1.0.8"

[dev-dependencies]
futures-lite = "1.12.0"
futures = "0.3.25"
criterion = { version = "0.3", features = ["async", "async_futures"] }
